### ISSUE TITLE
ECG is available in Japan.

### ISSUE THREAD

**Issue by mcaubrey** [einichi/is-apple-watch-ecg-in-japan-yet#2]
[Press release here!](https://www.apple.com/jp/newsroom/2021/01/ecg-app-and-irregular-rhythm-notification-coming-to-apple-watch/)

I guess they just haven't updated [the list](https://www.apple.com/watchos/feature-availability/#branded-ecg) yet.

**Comment by einichi** [comment]
Wooooo! Finally :D It took so long!

**Comment by mcaubrey** [comment]
Seems like so far it is only for people with beta profiles though?

**Comment by einichi** [comment]
Yeah. I've just re-enrolled by devices back into the beta program :)

**Comment by einichi** [comment]
And it's working!

**Comment by mcaubrey** [comment]
Great! I did the same but I haven't gotten to a charger yet so I can actually do the update.

**Comment by mcaubrey** [comment]
I installed the update and was able to use it a week ago but never posted here. Posting to close the issue.
